version: '3'
services:
  nginx:
    image: jwilder/nginx-proxy:latest
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    links:
      - tomcat
  tomcat:
    deploy:
      replicas: 1
    environment:
      VIRTUAL_HOST: localhost
      VIRTUAL_PORT: 8080
    depends_on:
       - db
    #volumes:
    #   - ./target/cis5530w3h1-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/cis5530w3h1.war
    build: ./
  db:
    image: mariadb:10.7
    ports:
        - 3306:3306
    volumes:
      - ./mounts/db_data:/var/lib/mysql
    environment:
      MYSQL_USER: mysql
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: page_monitor
      
    